project:
  type: website

website:
  title: "freds_music_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shaggycamel/music_blog
format:
  html:
    theme: minty
    css: styles.css

editor: visual

